# Copyright (C) CVAT.ai Corporation
#
# SPDX-License-Identifier: MIT

services:
  cvat_server:
    environment:
      AUTH_CONFIG_PATH: /home/django/auth_config.yml
    volumes:
      - ./auth_config.yml:/home/django/auth_config.yml:ro
